### ISSUE TITLE
bash not existing in device bin

### ISSUE THREAD

**Issue by rosemaryuser** [gitclone-url/Boot-image-Extractor#1]
so some device or maybe most devices don't come with bash in /system/bin so i modified the script to use the sh binary 
u can check it out 
its in txt btw coz github won't let me upload sh file
[boot-img-puller.txt](https://github.com/gitclone-url/Boot-img-puller/files/13930783/boot-img-puller.txt)

**Comment by gitclone-url** [comment]
Thank you for bringing this to my attention. You are right some devices may not have `bash` in the `/system/bin` directory due to reliance on toolsets like `BusyBox` or `Toybox`, which provide a set of Unix utilities along with their own shell interpreters. Anyway I'll update the shebang line to ensure the script utilizes the default root shell in Android.

**Comment by rosemaryuser** [comment]
another thing i forgot to mention is that the read -r -p dosen't work the same in sh compared to bash and u should change otherwise the script will keep giving an error saying "read -p nocoprocess"
 # Loop until valid input is provided
  while true; do
    # Ask the user to choose the boot slot image
    read -r -p "Which boot slot image would you like to pull? (a/b): " chosen_slot
to this
# Loop until valid input is provided
  while true; do
    # Ask the user to choose the boot slot image
    echo "Which boot slot image would you like to pull? (a/b)" 
    read chosen_slot

**Comment by gitclone-url** [comment]
@rosemaryuser  Are you really facing such issue? If possible, could you provide a screenshot?

Look i know that bash Provides additional features and improvements over sh, That's why when i first written this script I used  `#!/bin/bash` so that script  get executed in the bash shell. Yesterday when you told me about this issue , a question popped up in my mind at first, that this problem should not appear because in Termux, the usual location of /bin is /data/data/com.termux/files/usr/bin, also known as $PREFIX/bin. as #!/bin/bash was written in shebang line my script should look for bash binary in the /bin directory of termux, not in /system/bin. 
Later After thorough research, I concluded that the issue might occur only for users on older versions of Termux or other terminal emulators. I very clearly mentioned using Termux in my gist and provide a download link. But anyway even though i swiftly updated the shebang with /system/bin/sh, the script should still run on bash instead of sh shell based on my knowledge.   
Because In termux, if script has `#!/bin/sh` in the shebang line and you execute it with the "bash" command (`bash myscript.sh`), it will still be interpreted by the Bash shell. The shebang line is essentially a hint to the system on which interpreter to use, but when you explicitly invoke the script with "bash," it overrides the shebang. The shebang line is only processed by the system when the script is executed directly, not when it is passed as an argument to another program as far as i know.

So, in this case when a user will be running my script using `bash boot-img-puller` command (!clearly mentioned in my gist) on termux , the error "read -p nocoprocess" you mentioned should not appear because script will not run on sh shell. So If you are really facing the issue or you think that i am wrong or if there are specific points you'd like clarification on, please feel free to contact me on [telegram](https://t.me/PhantomXPain)
